### ISSUE TITLE
Meta Maint Not Radstorm Protected

### ISSUE THREAD

**Issue by vonzippenstein** [d3athrow/vgstation13#11634]
#### Description of issue

On Meta some areas of maint don't shield you from a radstorm.
_Killed me and was dragged to medbay by a skeleton miner asking what the happiest mask does. Before I could fully explain I was in crit. Spawned as a shade in medbay and couldn't help but laugh at my terrible luck._
The area doesn't flash green from radiation, looks like maint, has maint doors on all ends but is not protected.
#### Difference between expected and actual behavior

You mutate, build toxin damage, and die in an area that should be safe.
#### Steps to reproduce

Stand on maint on meta during a radstorm. Specifically the one listed below.
#### Specific information for locating

The maint area that surrounds the gateway. Next to mechanic's office. Above tech storage.
![scrnshot1](https://cloud.githubusercontent.com/assets/3376492/18034839/14a730fe-6d15-11e6-8caf-9a112c8bcd31.png)
#### Length of time in which bug has been known to occur

Specific time of the incident was August 28th at around 11:15 pm.
#### Server revision

6d7cb3a7af9ef0291b1f855a3b62321c93608c87
#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by FudgePucker** [comment]
In an unrelated note people who wear the happiest mask are idiots or assholes.

**Comment by Probe1** [comment]
Cannot reproduce, assumed fixed by #11974 

![dreamseeker_2016-11-29_08-33-51](https://cloud.githubusercontent.com/assets/8550416/20711642/bbc6808c-b60e-11e6-853d-41dc9a04e059.png)
