### ISSUE TITLE
Assorted map issues/requests

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#12002]
**All maps:**
- [ ] Metaclub's R&D features a shutter for the window that gave me an idea. What if the R&D labs on all stations featured a button that, when pressed, opened the doors to access science, rather than scientists constantly having to run out to open the doors for miners delivering ore, or whoever else?

**Box and Meta:**
- [x] Please give the mining outpost parity with Deff's, by moving (or adding) mining vendors to the asteroid station, and adding an ATM there for miners to use.
- [x] Deff's brig medbay features a single advanced medkit, which is pretty dope for quickly patching someone up at the brig without having to drag them all the way to medbay. It'd be nice if the other brigs featured something similar, or perhaps featured something of their own, like a surgery table with tools, or a bottle of assorted pills, or a welder and wires for robotic limbs, or just something to set them apart.

**Box Station:**
- [x] Unlike the other stations, there is no folder in virology to store the disease analyzer's printouts. Please add one.
- [x] Toxins storage has a tendency to leak gases when the canisters inevitably get opened by a rogue AI, borg, MoMMI, or whatever.

**Metaclub:**
- [x] There is no way whatsoever for a borer to escape xenobio under its own power. Xenobio atmos is completely isolated with no possible route of escape.
- [x] There is a complete surgery bay on the escape shuttle, but no bone setter. Please add a bone setter.

**Defficiency:**
- [x] The AI upload has Purge bolted into "High-Risk Module Storage" at roundstart, when Purge is frequently needed to clear ion laws or to successfully reset an AI whose laws have been modified to hell. Purge is only a high-risk module when used by a moron or an antag.  Strangely, there is also a windoor marked "Medium-Risk Modules" that contains a single Freeform module, yet there are TWO Freeform modules also locked up in "High-Risk Module Storage."
- [x] The manncrowave is behind firelocks and inaccessible in the event of an atmos alert.

I'm sure there's a lot more shit, but this is what I was able to remember tonight.

**Comment by CptWad** [comment]
>Toxins storage has a tendency to leak gases when the canisters inevitably get opened by a rogue AI, borg, MoMMI, or whatever.

zas is weird sometimes but I get what you mean, thats a code end thing and not due to a lack of barriers

>There is no way whatsoever for a borer to escape xenobio under its own power. Xenobio atmos is completely isolated with no possible route of escape.

Intentional, for whatever reason. I think its xenos.

**Comment by invoid9** [comment]
To add to this
Deff:

> service department has no chemmaster unlike box (and meta?), but its botany has 2 grinders (and another in kitchen) which seem completely useless.
> firelocks are extremely inconsistent in their placing. In the hall outside medbay all the way down to the vault, there are no hallway firelocks. No firelocks in any of the medbay entrances (except the morgue and genetics). Then, the cryo area is completely boxed off by firelocks, with the only way to take an occupant from the tube to the mancrowave is to move through two firelocks (out and then into the boxed off area). Firelocks in cargo lobby, but not the actual door. (Also no firelocks in or around AI core/upload, can't remember if that's a feature or not.)

**Comment by Kurfursten** [comment]
Deff also has 2 stills and its kitchen is way too cramped to waste on an extra still. I hate to cut down on maint but even just pushing out the kitchen one more tile would make the whole place feel a lot less cramped.

I do think you're wrong though @invoid9 I am pretty sure there is a condimasterneo in the chef backroom, although there may be no chemmaster in the botany backroom. They fill the same purpose though, so it may be intentional? You did say 'service' not 'botany', though.

**Comment by coldcola** [comment]
I may be wrong but I believe the HOS locker on deff doesn't have a dermal armour patch.

**Comment by invoid9** [comment]
Alright, if the condimasterneo functions like a chemmaster (I didn't try to use it because I GOT ANGRY) then I'm dumb, though I think my point about firelocks still stands unless it doesn't in which case I'm doubly dumb.

**Comment by Kurfursten** [comment]
No you're right those firelocks are garbage

**Comment by Blithering** [comment]
Meta HoP office is godly. Just want to mention that.

**Comment by Intigracy** [comment]
>There is no way whatsoever for a borer to escape xenobio under its own power. Xenobio atmos is completely isolated with no possible route of escape.

I believe he means even with the first of the two airlocks open, which is the normal escape route for the other two maps.

**Comment by Probe1** [comment]
(Box) Varies the syringes in Box Security Medbay from 3 inaprovaline to 1 charcoal, 1 anti tox, 1 inaprovaline, and throws in a bottle of happy pills (Space drugs + Sugar) for good measure

**Comment by Probe1** [comment]
Reworks firelocks around cryo to prevent manncrowave blockage …
Moved Purge board from HIGH RISK to Medium Risk storage.

**Comment by Probe1** [comment]
https://github.com/d3athrow/vgstation13/pull/12638

Added earmuffs and eyepatches to Security Medbay to satisfy the "MAKE IT DIFFERENT" tax
Added bonesetter to escape shuttle to complete the collection.
Added ATM to Metaclub Mining.

**Comment by ComicIronic** [comment]
Why is this even a monolithic issue - you should know better than to try and pile a load of unrelated map complaints into a single, potentially uncloseable, issue. It makes tracking next to impossible.

**Comment by Probe1** [comment]
I'm tracking it via citing it in my PRs and leaving a comment with what I changed.  

>Metaclub's R&D features a shutter for the window that gave me an idea. What if the R&D labs on all stations featured a button that, when pressed, opened the doors to access science, rather than scientists constantly having to run out to open the doors for miners delivering ore, or whoever else?

is actually the only aspect of the OP post that has yet to be addressed.

**Comment by Probe1** [comment]
I've closed almost all of this and the final one deserves an issue of its own so it gets proper views by other players and can be discussed.
