### ISSUE TITLE
Meta supply shuttle destroys maint

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#12027]
#### Description of issue

When trying to the supply shuttle on Meta, you get this message:
`ADMIN LOG: WARNING: supply shuttle (/datum/shuttle/supply) attempted to destroy Port Maintenance (/area/maintenance/fpmaint2). If you want supply shuttle to be able to move freely and destroy areas, change its "destroy_everything" variable to 1.`
This is **not** the same message as (#12023), that's a different issue. If you force destroy_everything to 1, this is what happens:
![destroys maint](https://cloud.githubusercontent.com/assets/5942183/18872084/d6ce0cc4-84b8-11e6-9f75-f6795f42b4b6.PNG)
It's too big to even fit in that hole and trying to force it results in torn walls.
#### Difference between expected and actual behavior

Meta's supply shuttle can't be moved because it breaks a wall into maint and depressurises the place.
#### Steps to reproduce

Load up maint
Send supply shuttle to station
#### Length of time in which bug has been known to occur

No ahelps or adminwarn messages about it for the entirety of yesterday, so I assume it's very recent.
#### Server revision

0e07cd0217834583181458ec75010de45fe43077
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues) Searched for: is:issue shuttle

**Comment by clusterfack** [comment]
@CptWad Pretty sure this is due to your change

**Comment by CptWad** [comment]
what the fuck

**Comment by JustSumBody** [comment]
![image](https://cloud.githubusercontent.com/assets/19365096/18904215/ea0846b6-852a-11e6-90d4-936f7123c0cf.png)
It's even worse on deff SEND HELP

**Comment by Kammerjunk** [comment]
Did you paste the same CentComm on all three stations?
I'm pretty sure they used to have different shuttles

**Comment by CptWad** [comment]
I actually think I fucked up the meta one when I made edits to centcomm (because what happened was that my pr was originally  fucked up due to compile errors but I redid it and had to do some copy-pasting) I noticed that the shuttles on meta and deff were fucked up by what I did so I just redid them
woops

this is fixed in my pr atm
