### ISSUE TITLE
issues and ideas from the discord

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#14026]
Listing these mostly for myself so I don't have to keep 50 notepad files open.

- [x] *ghetto space suits are better in every way than civilian space suits* #14103
- [x] *firesuits and heaters allow you to traverse space ez* can't fix
- [X] *firesuits don't cover hands which allows you to scrubglove with them* false
- [x] *the mining vending machine isn't access restricted* #14028
- [x] rigged crates zap you even if you've got insulated gloves
- [x] *mesons and thermals give you flash protection when it should be quite the opposite* #14034
- [ ] adamantine and mythril coins can't be made even though adamantine and mythril sheets exist
- [ ] add adamantine sheets to finds.dm L241
- [x] *wizard robes can't hold staffs* #14030
- [x] *staff of change doesn't have an unique sprite even though we have one* #14030
- [x] *staff of necromancy is a different size than the other staffs* #14030
- [ ] coin bags need work (coin rustle noise on hit if filled, make it do actual damage)
- [ ] find a use for all the unused sprites in gun.dmi
- [ ] find a use for all the unused sprites in wizard.dmi
- [x] standard (engineering) switchtool is completely unused
- [x] *MaMIs are unused* #14100
- [ ] Add sound for cargo shuttle arriving
- [ ] Add a single-use low-pressure impact grenade for miners
- [x] Disposable Emergency Breaching Tool, AKA Sec RPGs
- [ ] STALKER small artifacts for xenoarch (speed up excav suits, remove radiation, etc)
- [x] *plant-b-gone has a different offset than the normal sprayer*  #14328
- [ ] neo-russian boots sprite off-center when worn
- [x] *board descriptions*  #14330
- [ ] record computers can't delete records
- [ ] instagib arena mode
- [ ] make rogue drones drop borg modules instead of random boards
- [x] add a golden fucking hemostat to make medical testing less shit
- [x] add uncolored toolboxes to autolathe
- [x] ~~add combat toolbox to protolathe~~
- [ ] port dufflebags
- [x] code space un-slipping liquid (Space abrasant / frictionizer)
- [x] make unique sprite for Starscreen-EX
- [x] make starscreen generators not go through the animation when you see them for the first time
- [x] unfuck starscreen cargo crates
- [x] code hypozine; syndicate hyperzine that makes your heart explode
- [x] _change syndicate creatine suicide pills to contain 30 creatine, 5 oxycodone, 5 dexalinplus, 5 hypozine, 0.4 mednanos and 4.6 combatnanos_ #15355
- [x] make starscreen circuit board solderingironable into a starscreen EX and vice versa
- [x] update mediborg roller bed sprite and deployed sprite
- [x] remove N2 tanks from O2 lockers
- [x] update starscreen sprite
- [ ] stasis (NOREACT) eclairs (or other food)
- [x] smart glass (transparent/opaque/one-way)
- [ ] smartglass floors (toggle them as lightswitch)
- [ ] Mecha hardpoints (two arms, some internals) to replace the current module system
- [ ] Proper mecha startup sounds
- [ ] Mecha interaction with adjacent machinery
- [ ] ECM / Radio-and-computer jammers, portable or wrenched machinery
- [ ] Make mecha weapons man-portable (Lost Planet!)
- [ ] Fully modular mecha a lá that one underwater codebase
- [ ] Chaff! Paper + ground aluminum, to fuck up silicon vision with

**Comment by Cisrox** [comment]
I'm pretty sure that if you have thermals on and get flashed you get eye damage

**Comment by Killette2** [comment]
I always wore staff of X on my back. Wearing your staff on your back separated the boys from the men. You don't need a backpack as a wizard anyways, you're just gonna be a faggot and put guns in it when you already have magic powers.

**Comment by SonixApache** [comment]
@Killette2 you obviously don't know about my wizardly three-staff-army tactics

**Comment by Shadowmech88** [comment]
>even though adamantine and mythril sheets exist

I'm pretty sure they're unobtainable.

**Comment by SonixApache** [comment]
@Shadowmech88 you can get mythril from xenoarch (unless that got changed recently?) and I dunno about adamantine.

**Comment by Killette2** [comment]
I don't think you could get them from xenoarch for a long time, but they used to be created from breaking alien shit

**Comment by PJB3005** [comment]
You can definitely still get them.

**Comment by SonixApache** [comment]
mythril is obtainable through xenoarch
adamantine isn't obtainable but i can put it in the finds list since it doesn't do anything

**Comment by SonixApache** [comment]
gonna close this since i can find it for myself whenever

**Comment by Allspice** [comment]
Remove N2 tanks from oxylockers when

**Comment by ghost** [comment]
Nerfing vox magboots when? They have ZERO (0) downsides.
