### ISSUE TITLE
Meta Cargo Shuttle burns up

### ISSUE THREAD

**Issue by ConkerDev** [d3athrow/vgstation13#15816]
The Cargo Bay Shuttle on Meta starts burning up whenever the Mining shuttle starts its launch. The fire seems to just go through the shuttle windows

Game: cefb6722e6ef8fc5c7e510e61dec11a74e4d88e5 
Patches: cce7d45130404579663c09010c5d0aebe829e6d6 

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Duny-** [comment]
I'm gonna need more information on this because I am failing to see how that's even possible
![image](https://user-images.githubusercontent.com/5224390/30143277-41bf4576-9385-11e7-8d5c-fd184348cb46.png)

**Comment by DamianX** [comment]
I'm fairly sure this is referring to meta instead.

**Comment by ConkerDev** [comment]
You are quite right. Editing
