### ISSUE TITLE
Metaclub Mining Outpost Doors set to Science Outpost Airlock Configuration

### ISSUE THREAD

**Issue by Rhimrifer** [d3athrow/vgstation13#17033]
I have no idea why this still exists, but here we are.

#### Description of issue
Both of the mining doors leading out to the east of the mining outpost have the same configuration as the exterior science outpost airlock. This leads to them bolting closed/open when the science outpost airlock is cycled or forced.

#### Difference between expected and actual behavior
Expected mining outpost doors to have their own airlock configuration or not at all
Actually they are setup the same as one door in the science outpost airlock.

#### Steps to reproduce 
-Operate the science outpost Airlock Controller
-Observe the east mining outpost External Airlock

#### Specific information for locating
Airlock controller is on the science outpost in Expedition Preparation
Airlocks incorrectly configured are the External Airlocks in Mining Station EVA
All doors are on frequency 1331

#### Length of time in which bug has been known to occur
As long as I've played

#### Server revision
40962d22a5040090760baae3b2e3f5f2e20f7781

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)
