### ISSUE TITLE
Custtom strike teams wishlist

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#22477]
- [x] Option to spawn strike teams naked ( #20973 ) #22671
- [ ] Option to choose custom strike team species
- [x] Transfer chosen strike team name to faction name #22673
- [x] Transfer chosen objective to faction objective #22677
- [x] Show chosen objective right under the "[X] needs YOU" line so ghosts know what they're signing up for #22674
- [ ] Make -1 option for gear spawners actually work
- [x] Does the name option even do anything?
- [x] [SubtleMessage Entire Team] button #30267

**Comment by ShiftyRail** [comment]
Answer to all this is probably outfit datums

**Comment by DeityLink** [comment]
huh, they used to spawn naked by default, what is this shit.

**Comment by DeityLink** [comment]
strike `[SubtleMessage Entire Team] button`
