### ISSUE TITLE
The big list of things that are broken with malf

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#23072]
- [x] ~~Still no way to prevent shuttles - calling it essentially means game over for the malf~~ - sort of fixed in #26286
- [x] ~~Winning as malf and not nuking lists you as failed. Maybe because you didn't set off a nuclear device?~~ #35028
- [x] ~~The [Hack] button on the cyborg console doesn't do anything. You can't hack borgs.~~ #27176
- [x] Borgs still get access to the nuke button, even though it may or may not actually work
- [x] Pressing the nuke button while shunted does *nothing*.
- [x] ~~Setting off the nuke ends the round but it also kills you, which then causes the gamemode to consider you dead, so the round ends *twice* and it plays the "good job crew, you killed the AI" announcements~~ fixed in #27727
- [x] ~~Shunted AIs can't press their roundender buttons which is annoying as hell~~ - fixed in #26446 
- [x] Getting killed as a shunted AI between the 'You win!' stage and the actual smelelelel puts the round into extended hell
- [x] You can get pulled for malf if you have malf enabled but have AI disabled in your job prefs. (intended)
- [x] You can get pulled for malf if you are AI job-banned (according to @DamianX ) #36621
- [x] ~~the timer is TOO FUCKING LONG~~ #27669
- [x] Midround malf ruleset is very fucking broken:
- [x] - Malf itself doesn't get put into the faction
- [x] - Malf itself doesn't get any of their powers
- [x] - Malf itself doesn't even get the fucking malf law properly
- [x] - ~~Slaved borgs don't get the proper role (and thus don't get in the faction and don't get actual antag status if they even do get the malf law properly)~~ #30161

**Comment by Kharkov72** [comment]
mmmmm spaghetti

**Comment by boy2mantwicethefam** [comment]
FEATURE

**Comment by SonixApache** [comment]
also i'm not 100% on it but it seemed to me like APCs weren't lowering the victory timer at all

**Comment by TurboGay** [comment]
> 
> 
> also i'm not 100% on it but it seemed to me like APCs weren't lowering the victory timer at all

The diminishing returns are pretty brutal on the timer being lowered, was this hacking early on or after a bunch? Because after the first 6-10 or so it barely lowers the timer.

**Comment by ShiftyRail** [comment]
Malf AIs shouldn't be able to recall

**Comment by SonixApache** [comment]
shuttle should auto-recall on malf

@TurboGay he hit delta with about 8 APCs and the timer started at 1800 and went down normally. Ended at 12, didn't do much either.

**Comment by gurfan** [comment]
wasn't 

>  Pressing the nuke button while shunted does nothing.

fixed

**Comment by ghost** [comment]
borgs getting access to the nuke button is really really fun when most of the crew is autoborged and everyone scrambles to click that new spell button before someone selects nuking within 1 second, FEATURE

**Comment by pedr69** [comment]
> Pressing the nuke button while shunted does nothing.

false
i exploded the nuke while shunted and also unpowered and dying no problem

**Comment by pedr69** [comment]
and the "2 AIs spawn sometimes, one malf and one non-malf" is happening again recently

**Comment by SECBATON-GRIFFON** [comment]
borgs don't have access to the nuke button and a dead shunted ai in the victory wait period doesn't block the round anymore, update that
