### ISSUE TITLE
New Job: Angler - Systems, Gameplay and Progress

### ISSUE THREAD

**Issue by GreatBigFailure** [d3athrow/vgstation13#27984]
Angler is getting close to completion now that my 2 month "Oh god I've done nothing but code fish for 12 hours a day" break is over. I'm writing this second issue primarily to help me organize my thoughts but also to show progress, be a copy paste explanation, and of course to get feedback.

This issue is on the actual gameplay and systems, a broader overview of theme and purpose can be found here: https://github.com/vgstation-coders/vgstation13/issues/27105

### **General Gameplay**
Obviously casting your rod and catching fish is a major part of the job, but anglers will spend just as long gathering bait and trading with other departments. This means you won't be out in space all alone constantly. More details on the bait system later. 

You decide and gather your bait. You setup your traps, cast your rod, and when a fish is hooked you reel it in. You scan it and if you see fit you shove it in the analyzer. Then you either keep it alive for a "living use" or kill it for a "butcher use". 

**Avoiding Singleplayer**
Essentially you'll have both a rod and fish traps. The rod is for actively catching and will be the most efficient method. At shift start it will require your focus. 

- Rods:

Wormhole tech rods will reel a catch to where you cast the rod. Bluespace will reel it to where you are when reeling in. This means that as you progress you're a little less grounded.

- Traps

Traps will be less efficient than rods time-wise but only require you place them, add bait, and leave them be. They'll also use more bait than rods. I'm considering making them more efficient if there are no humans around too.
These are obviously to promote leaving your post and delivering goods, collecting things for your job, and generally joining the round. If a miner isn't on the roid he isn't mining, if xenobio isn't in their lab they aren't sliming. Both those jobs are very isolated and singleplayer. Not necessarily a bad thing for them but I'm trying to avoid that with angler.

- Fishing (worm)hole

Later in the round science will be able to produce a fishing hole machine that allows anglers to cast into it as if they were casting into space. So anywhere you can anchor the machine can be your fishing spot, comfy fishing bars sound nice.

### **Bait System**

This is the foundation of the job. 
Bait will decide what you catch, the quality of the catch, possible mutations, additional effects, how long the catch takes, the list goes on. A beginner angler using whatever bait VS an experienced one with autism bait will be night and day. 

A large list of items, including almost everything the angler catches, will be given bait values. If an item has those values, you can attach it to your rod and use it as bait. So technically an angler can be self sufficient by just sticking whatever guppies he gets to his rod and hoping for a Star Drake or Bionivalve Reclammer.
That angler won't be too successful though. The chef will be given recipes to combine an amount of bait into a single super-bait. It's still being decided exactly how they combine them but the placeholder method is a new type of dough -> add bait -> microwave -> bait ball. 

**Fish VS Salvage**

In the previous issue I explained the difference between mob fish, item fish, and salvage.
Bait will, for the most part, not distinguish between mob and item fish. Really that difference exists to reduce effort for myself and spriters. It will however differentiate between fish and salvage.
While bait will have a lot of numbers behind what fish you catch and how good those fish are, salvage will be primarily RNG. The only currently coded and planned interaction between bait (and thus the angler) and salvage is the "magnetism" stat which will make catching salvage, ignoring rarity, type, etc, more common.
So while a fish focused angler can tinker with his catch pool, a salvage focused angler is totally at the mercy of RNG. 

**Exploration and Butchering**

Since this is about gameplay I felt the need to mention different Z levels will make different catches more or less common, so angler will have reason to go to Z levels besides 1 and 5. Butchering is a major focus of the job as well as the bulk of catches were designed to be more commonly useful when killed and butchered as to prevent 100 fish ruining the aesthetic of the station. 

### **Give Feedback**
I'd have been done already if all I had to do was code. Brain hurts from thinkin about fish.

### **To-Do**

These are far from equally weighted. The "catch stuff" section is thousands of lines of code and the vast bulk of the work. Fish trap code, for example, will only take a few hours tops. I'm also likely forgetting things.

**Catch stuff**
- [x] Mob fish code
- [x] Mob fish sprites
- [x] Mutation code 
- [x] Item fish code
- [x] Item fish sprites (About 70% done)
- [ ] Salvage list

**Equipment**
- [x] Rod code
- [x] Fish trap code   
- [x] Catch code
- [x] Equipment (harpoon, knife, etc) code
- [x] Equipment (including rod/trap) sprites
- [x] Machine code (analyzer, fishing hole)
- [x] Machine sprites 

**Bait**
- [x] Bait system backbone
- [x] Chef stuff
- [ ] On-release bait list

**Oh heck a new job**
- [ ] Mapping
- [ ] Role stuff
- [ ] I think I have to ask Pomf nicely or something

**The nightmare I've chosen**
- [x] Rework butcher code so it isn't inflexible ass

- [x] A little testing
- [ ] A lot of testing

[wip]

**Comment by cloutcode** [comment]
i love you

**Comment by GreatBigFailure** [comment]
Butcher rework done

**Comment by Eneocho** [comment]
Still waiting.

**Comment by Eneocho** [comment]
https://www.youtube.com/watch?v=qO-mSLxih-c&ob=av2e

**Comment by Eneocho** [comment]
Symbolic bump.

**Comment by GreatBigFailure** [comment]
Still working on this, don't worry. Progress is slow but steady. Pretty soon I'm moving much closer to my work so I'll have more free time as well. Once that happens I plan on finishing my current projects then putting Angler in the spotlight again, hopefully until it's completed this time.

**Comment by Eneocho** [comment]
good luck

**Comment by Eneocho** [comment]
Can you add a space white whale (Möbius Dick) boss level mob for the Captain Ahab gimmicks? @GreatBigFailure

**Comment by Eneocho** [comment]
If you do end up adding a space white, I'd make it basically a reskin of Angie that can move through space like a carp (with some cool visuals, like Mobius Dick on that one futurama episode) and it travels between Z-Levels. Meaning you have to chase it across space to catch-kill it. To track it, you have to use a GPS as bait. If you beat it, you get the heart of the beast that gives you some cool power (maybe a toggle-ability to phase between space and bluespace. Effectively a reskin of the wizard's jaunt spell) when held, a harpoon-like weapon and a music disk with sea shanties. @GreatBigFailure

**Comment by Eneocho** [comment]
Symbolic bump.

**Comment by Eneocho** [comment]
It's over. I had hope but it's over.
Could you release the code you had of angler so it could be implemented somehow?

**Comment by west3436** [comment]
GreatBigFailure has gone fishing and never returned to Angler role development.
