### ISSUE TITLE
Moody light todo list

### ISSUE THREAD

**Issue by SECBATON-GRIFFON** [d3athrow/vgstation13#36992]
[featurerequest]

some stuff i noticed could use them:

- [x] microwaves (including an on sprite)
- [x] virology machinery that's not the disease splicer
- [x] SMES
- [ ] lockers and crates with locking mechanisms
- [x] gas canisters
- [x] the nuke
- [x] heaters and freezers
- [ ] light tubes and bulbs themselves

@DeityLink

**Comment by SECBATON-GRIFFON** [comment]
part completed by #38520
